version: "3"

services:
  backend:
    build:
      context: ../source-repo/backend
    ports:
      - "8800:8800"
    environment:
      DATABASE_HOST: ${RDS_HOST}
      DATABASE_USER: ${RDS_USER}
      DATABASE_PASSWORD: ${RDS_PASSWORD}
      DATABASE_NAME: ${RDS_NAME}
      DATABASE_PORT: ${RDS_PORT}
    depends_on:
      - frontend

  frontend:
    build:
      context: ../source-repo/frontend
    ports:
      - "80:80"
    depends_on:
      - backend