version: "3.8"

services:
  frontend:
    image: ${AWS_ECR_REPO}:frontend-latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ${AWS_ECR_REPO}:backend-latest
    container_name: backend
    restart: always
    environment:
      - RDS_HOST=${RDS_HOST}
      - RDS_USER=${RDS_USER}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_NAME=${RDS_NAME}
      - RDS_PORT=${RDS_PORT}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
