version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ../source-repo/backend
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
    environment:
      DATABASE_HOST: ${RDS_HOST}
      DATABASE_USER: ${RDS_USER}
      DATABASE_PASSWORD: ${RDS_PASSWORD}
      DATABASE_NAME: ${RDS_NAME}
      DATABASE_PORT: ${RDS_PORT}

  frontend:
    container_name: frontend
    build:
      context: ../source-repo/frontend
      dockerfile: Dockerfile
    environment:
      VITE_BOOK_API_BASE_URL: https://claudio.works/api
    ports:
      - "5173:5173"
    depends_on:
      - backend