version: "3"

services:
  backend:
    container_name: backend
#    build:
#      context: ../source-repo/backend
#      dockerfile: Dockerfile
    image: backend-app:latest
    ports:
      - "8800:8800"
    env_file:
      - /home/ec2-user/.env

  frontend:
    container_name: frontend
#    build:
#      context: ../source-repo/frontend
#      dockerfile: Dockerfile
    image: frontend-app:latest
    env_file:
      - /home/ec2-user/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend