version: "3"

services:
  backend:
    build:
      context: ../source-repo/backend
    ports:
      - "8800:8800"
    environment:
      DATABASE_HOST: ${RDS_HOST}
      DATABASE_USER: ${RDS_USER}
      DATABASE_PASSWORD: ${RDS_PASSWORD}
      DATABASE_NAME: ${RDS_NAME}
      DATABASE_PORT: ${RDS_PORT}
    networks:
      - app-network

  frontend:
    build:
      context: ../source-repo/frontend
      dockerfile: Dockerfile.prod
    volumes:
      - frontend_dist:/app/dist
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_dist: