version: "3.8"

services:
  frontend:
    image: ${AWS_ECR_REPO}:frontend-${RC_LABEL}
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_BOOK_API_BASE_URL: https://claudio.works/api

  backend:
    image: ${AWS_ECR_REPO}:frontend-${RC_LABEL}
    container_name: backend
    ports:
      - "8800:8800"
    environment:
      RDS_HOST: ${RDS_HOST}
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_NAME: ${RDS_NAME}
      RDS_PORT: ${RDS_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
